# ASM source files
ASRC +=

# C source files
CSRC += src/CommandLine.c \
        src/Hardware.c \
        src/Joystick.c \
        src/MinxAudio.c \
        src/MinxCPU.c \
        src/MinxCPU_CE.c \
        src/MinxCPU_CF.c \
        src/MinxCPU_SP.c \
        src/MinxCPU_XX.c \
        src/MinxColorPRC.c \
        src/MinxIO.c \
        src/MinxIRQ.c \
        src/MinxLCD.c \
        src/MinxPRC.c \
        src/MinxTimers.c \
        src/Multicart.c \
        src/PMCommon.c \
        src/PokeMini.c \
        src/Video.c \
        src/Video_x1.c \
        src/Video_x2.c \
        src/Video_x3.c \
        src/Video_x4.c \
        src/Video_x5.c \
        src/Video_x6.c \
        src/Video_x7.c \
        src/freebios.c \
        src/PokeMini_ColorPal.c \
        src/memory_stream.c \
        src/main.c

# Additional include paths
IPATH += -Isrc

# Path to root directory from the project directory
PICO_ROOT_PATH = ../..

# Include PicoLibSDK library headers
IPATH += -I${PICO_ROOT_PATH}/_lib/inc

# C++ source files
SRC +=

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
