# ASM source files
ASRC +=

# C/C++ source files
SRC += $(wildcard src/pokemini/*.c)
SRC += src/main.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
